### ISSUE TITLE
Disable in responsvie

### ISSUE THREAD

**Issue by sabuz** [emn178/jquery-stickit#10]
Hello!
This plugin sometime create problem in responsive design, and it is not needed in some case in responsive design.
So, It would be great if there were any option to disable it in responsive design.

**Comment by emn178** [comment]
Hi,

Currently, you can try to use destroy method to remove sticky effect.
```JavaScript
element.stickit('destroy');
```

**Comment by emn178** [comment]
Hi,

You can use `screenMinWidth` and `screenMaxWidth` option in v0.2.0 for RWD now.
Please try it.

**Comment by rorc** [comment]
I use this:
```
    aside.stickit();

    $(window).on('load resize', function() {
        if ($(this).width() < 768) {
            aside.stickit('destroy');
        }
    });
```

**Comment by emn178** [comment]
Yes, you can use @rorc 's solution before v0.2.0.
If we can fix your problem, please close this issue, thanks.
