### ISSUE TITLE
A little bug with text expander

### ISSUE THREAD

**Issue by Redani** [emn178/jquery-stickit#11]
Hi, and thanks a lot for this lovely plugin :)

I've noticed a small bug that occurs when the sticky menu is used with a text expender (readmore).
when I click on "read more" the text expends, i scroll down and the sticky menu works fine (img 1), but when i close the text "view less", the sticky menu don't update and stays where it was before (img2)
Hope i made myself clear :D

Thanks for your support

<img width="1440" alt="screen shot 2015-11-29 at 12 53 58" src="https://cloud.githubusercontent.com/assets/328526/11457076/6fcfceaa-9697-11e5-8951-63c8ba5c7ef9.png">
<img width="1440" alt="screen shot 2015-11-29 at 12 54 11" src="https://cloud.githubusercontent.com/assets/328526/11457077/6fd75300-9697-11e5-90ec-c9a562eae394.png">

**Comment by emn178** [comment]
Hi,

Can you give me your url?

**Comment by Redani** [comment]
OMG, sorry for not replying, i didn't get any notification. I just by chance checked this page...
I'll PM you the url with this issue.

thanks a lot for your support

**Comment by emn178** [comment]
Hi,

jQuery-stickit detects when scroll event only. It does not know the container height changed. 
Currently, you can trigger scroll event to force update after height changed by 
```JavaScript
$(window).trigger('scroll')
```

I will try to handle this case in the future.

**Comment by Redani** [comment]
Oh that's awesome :) you made my day :)
Thank you very much for your help and also for this amazing plugin ;)

Happy holidays
Reda

**Comment by Redani** [comment]
Hi Again, hep you're doing well.

I've just realised that the solution you gave me doesn't work on safari :/ I updated the script to th new version but still doesn't work :( Any idea how to fix this?

Thanks

**Comment by emn178** [comment]
I run script in console manually and it can work. So it seems that you trigger before collapse. 
I think that Safari render a little slow so that causes this.
Please make sure that you trigger after collapse.

**Comment by Redani** [comment]
Thanks for the very fast reply :)
Oh yes, you are right, trigging it after collapse works great, didn't think about it :D 
Are you planing to add this fix directly into the plugin?

**Comment by emn178** [comment]
v0.2.2 added some features to detect more cases. It could handle your case but old IE browsers does not support...

**Comment by Redani** [comment]
Cool, thank you very much!
I'v also noticed some weird behaviors. I'll PM you the URL and details.
Thank you
