### ISSUE TITLE
AutoHeight

### ISSUE THREAD

**Issue by rorc** [emn178/jquery-stickit#12]
Hello!
Will be nice add option to set auto max height for sidebar...
Thanks :P

**Comment by emn178** [comment]
What do you mean?

**Comment by rorc** [comment]
Look this: [http://endlessswim.ru/](http://endlessswim.ru/)
http://joxi.ru/v29Jq3ocOpXEAG and http://joxi.ru/8An0REOH8yxEmO

**Comment by emn178** [comment]
Do you mean that it can not show the bottom of sidebar in http://endlessswim.ru/ unti it is end of page?
I don't understand what the other two urls mean.

**Comment by rorc** [comment]
Need fit sidebar height to window height during scrolling.

**Comment by emn178** [comment]
Currently, if sidebar height is greater than screen, it will scroll sidebar.
I don't know what the exact behavior is "fit to window". Please describe more.

**Comment by rorc** [comment]
http://joxi.ru/Dr8nJRjHpM3126

**Comment by emn178** [comment]
I realized the urls are screenshot. I thought they are your web site..
Ok, I understood your problem. I will think about it.

**Comment by rorc** [comment]
Ok, thanks :P

**Comment by emn178** [comment]
Why not to fit window height at beginning?
Look like this:
https://jsfiddle.net/kpn3c2zu/1/

**Comment by rorc** [comment]
Thanks, but its tables...
I try to use flexbox...
