### ISSUE TITLE
Stick spacer are not destroy

### ISSUE THREAD

**Issue by rorc** [emn178/jquery-stickit#16]
http://joxi.ru/nAyXNvoTVy912Z

Stick spacer adds empty space even if block are not stuck.
This happens after onUnstick.

**Comment by emn178** [comment]
Hi,

spacer set display:none if not stuck, so it should not show.
Is there a "display: block !important" in your classes?

BR.

**Comment by rorc** [comment]
Yea, stickit spacer extend all styles from original container.
Bootstrap .visible-xs uses display: none with !important.
So, stickit must set display: none with !important too :)

**Comment by emn178** [comment]
Hi,

v0.2.5 should fix this problem.

**Comment by rorc** [comment]
Ok, thanks!
