### ISSUE TITLE
Strange in use settings

### ISSUE THREAD

**Issue by rorc** [emn178/jquery-stickit#17]
New settings system some strange and inconvenience...
Why not working this?
```
    $('.list-of-tariffs').stickit({
        top: 40,
        screenMinWidth: 544,
        scope: StickScope.Document
    }, {
        top: 0,
        screenMaxWidth: 768
    });
```
It is assumed first object of settings will use always and if screenMaxWidth: 768 then top is 0, but this not working :(

**Comment by emn178** [comment]
Hi,

Do expect this settings?
```JavaScript
< 544
```JavaScript
    {
        top: 0
    }
```
544 ~ 768
```JavaScript
    {
        top: 0,
        scope: StickScope.Document
    }
```
> 768
```JavaScript
    {
        top: 40,
        scope: StickScope.Document
    }
```
```

**Comment by emn178** [comment]
Hi,

Previous versions use default values to merge and get wrong result. 
v0.2.6 fixed this problem and should work.
Please try it.

Thanks.

**Comment by rorc** [comment]
According documentation, first object is global and work all time.
I expect stickit will destroy when screenMinWidth: 544, but now (v0.2.6) he still work without this:
```
{
        top: 40,
        scope: StickScope.Document
}
```

**Comment by emn178** [comment]
"first object is global and work all time." is not correct.
the correct thing is that it will apply all if screenMinWidth and screenMaxWidth are unset.
The design is similar with CSS.

And your setting should get the result as I commented above.
If the result is not what you want, you should change the settings.
or you can describe what you want.

**Comment by rorc** [comment]
I want destroy stickit if screenMinWidth < 544px;
I want top: 40 and scope: StickScope.Document as default;
I want top: 0 if screenMaxWidth < 768px.

Thanks :)

**Comment by emn178** [comment]
ok, what you want is:
544 ~ 767
```JavaScript
    {
        top: 0
    }
```
\>= 768
```JavaScript
    {
        top: 40,
        scope: StickScope.Document
    }
```
544 ~ 767 means
```
screenMinWidth: 544,
screenMaxWidth: 767,
```
\>= 768 means
```
screenMinWidth: 768,
```
so your final setting should be
```JavaScript
    $('.list-of-tariffs').stickit({
        screenMinWidth: 544,
        screenMaxWidth: 767,
        top: 0
    }, 
    {
        screenMinWidth: 768,
        top: 40,
        scope: StickScope.Document
    });
```

**Comment by rorc** [comment]
Ok, thanks, its work, but inconvenience to use.
If i need more options, i need dublicate their in all objects for all screens?

**Comment by emn178** [comment]
Hi,

The usage is same with media query. You need to define or overwrite css for each screen size.
The option is also can apply all screen size depends on how you use. 

For example, if you want:
544 ~ 767
```JavaScript
    {
        top: 0
        scope: StickScope.Document
    }
```
\>= 768
```JavaScript
    {
        top: 40,
        scope: StickScope.Document
    }
```
You could write this:
```JavaScript
    $('.list-of-tariffs').stickit({
        screenMinWidth: 544,
        screenMaxWidth: 767,
        top: 0,
        scope: StickScope.Document
    }, 
    {
        screenMinWidth: 768,
        top: 40,
        scope: StickScope.Document
    });
```
But you could also write this, it will get the same result:
```JavaScript
    $('.list-of-tariffs').stickit({
        screenMinWidth: 544,
        top: 0,
        scope: StickScope.Document
    }, 
    {
        screenMinWidth: 768,
        top: 40
    });
```

**Comment by rorc** [comment]
Ok, big thanks, now i understand :)
