### ISSUE TITLE
Add double-scrolling 

### ISSUE THREAD

**Issue by Lisennk** [emn178/jquery-stickit#18]
Library is widely used to stick sidebar along content and I think it will be good feature, if it will take two selectors and stick the lower one, because sometimes sidebar is higher than content.

Possible syntax:
`$('#sidebar').stickit({with: '#content'});`
`$.stickit('#content', '#sidebar')`

**Comment by emn178** [comment]
I will consider it when I have time.

**Comment by galitskye** [comment]
Thanks!

2016-06-21 17:11 GMT+03:00 emn178 <notifications@github.com>:

**Comment by emn178** [comment]
Hi,

New version v0.2.8 should support this feature.
You can simply stick the different elements which have the same parent.
You can see the demo https://emn178.github.io/jquery-stickit/samples/columns/
