### ISSUE TITLE
YouTube embed bug 

### ISSUE THREAD

**Issue by Lisennk** [emn178/jquery-stickit#20]
Can't enable full-screen mode in YouTube embed video inside sticky element. 
![pasted](https://cloud.githubusercontent.com/assets/8103985/16444582/5e105e4e-3de7-11e6-92b6-8c0b89cefcd5.png)
Screen related: as you see, video is expanded on sticky element, but not in full screen.

**Comment by emn178** [comment]
It seems that a CSS property causing this, and it was for the other problem.
I will try to figure it out when I have time...

Thanks for report.

**Comment by emn178** [comment]
Hi,

It should be fixed in new version v0.2.7. Please try it.

Thanks.
