### ISSUE TITLE
Only works with scope: StickScope.Document ?

### ISSUE THREAD

**Issue by jezthomp** [emn178/jquery-stickit#21]
I can only get this working using StickScope.Document, if i try StickScope.Parent it doesn’t stick.

From viewing in the inspector just seems to change the position to ‘absolute' rather than ‘fixed’?

Does the parent need to have an id or set width as i’m using percentage based grid?
`$('#sticky_column').stickit({
		screenMinWidth: 740,
		scope: StickScope.Document
		});`

It seems to initialise but unless StickScope.Document it just remmed absolute rather than fixed?

**Comment by emn178** [comment]
Hi,

Can you give a sample code?

**Comment by jezthomp** [comment]
My apologies i had put #sticky_column on the inner container rather than the actual column that i wanted to be stuck.

**Comment by EDsolution** [comment]
Is it possible to set custom parent? No the actual parent of the stiicky elemnt, but parent of the parent.

Thanks.

**Comment by emn178** [comment]
hi, @EDsolution 
I will try to add this feature in the future.
You could create a new issue to note this.
