### ISSUE TITLE
Bug with iframe fullscreen

### ISSUE THREAD

**Issue by rorc** [emn178/jquery-stickit#22]
Hi again :)
Look this http://stolyarych.moscow/galereya
Scroll down for stuck green headers and press some green button http://joxi.ru/DrlOZgRFQKQ5AP.
Then go to toutube fullscreen mode and exit from fullscreen and look strange offset right http://joxi.ru/1A597KvtE4EEAE

**Comment by emn178** [comment]
Hi,

I can reproduce sometimes. I will try to fix this when I have time.

Thanks.

**Comment by emn178** [comment]
Hi,

It should be fixed in the new version v0.2.7. Please try it.

Thanks.

**Comment by rorc** [comment]
Yes, its fixed, thanks :)
