### ISSUE TITLE
Stick only after offset

### ISSUE THREAD

**Issue by rorc** [emn178/jquery-stickit#24]
Hi :)

Sometimes need to stick panel after scroll offset top.
In my case first wheel scrolls down to bottom automatically, and stick panel covers info: http://joxi.ru/eAO4PzGtllbQro => http://joxi.ru/12MQPzlfQQQV2J
Will be nice improve stickit, adding option like _stickIfOffset_
In my case i want to start stick only after scroll offset top = `$(window).height() + 200`

Thanks :)

**Comment by emn178** [comment]
I will think about it.

**Comment by rorc** [comment]
Oh, sry, its not need. I should be calculate scroll `200 - heightOfnav`.
