### ISSUE TITLE
Spacer width incorrect on refresh

### ISSUE THREAD

**Issue by PieterAkkerman** [emn178/jquery-stickit#27]
Hi there,

Thanks for this great piece of code.

When I test under Chrome and Firefox (OSX) the spacer.width() seems to be calculated incorrectly.

It only happens when I refresh the page when it's scrolled half way down (line 394 and sets an incorrect width based on spacer.width()). When scrolling to top or on resize the issue gets fixed.

Any idea how to fix this?

**Comment by emn178** [comment]
Hi,
what is your jquery version? can you give me url?
I found jquery maybe have some problems before version 2.1.3. 
and 3.0.0+ is better.

**Comment by PieterAkkerman** [comment]
Hi there, thank you for your reply.

Just upgraded my jquery from 1.10.2 to 3.1.1 and it fixed the issue!

Adding:

if (this.lastValues.width == null){
this.lastValues.width = spacer.width();
} else

Before line 394 fixes the issue on the old jquery version

All the best from Holland,
Pieter
