### ISSUE TITLE
Top (offset) problem

### ISSUE THREAD

**Issue by PieterAkkerman** [emn178/jquery-stickit#32]
Simple example:
https://www.pxlite.com/test.php

Using $('.sidebar').stickit({top: 200});

Resize screen to around 700px wide to see the stick / unstick happen

This is the moment the difference in height between .content and .sidebar is equal or less then 200px. It looks like the offset is added to the height of the .sidebar

Hope you can help me out.

**Comment by emn178** [comment]
Hi,

Change this line
https://github.com/emn178/jquery-stickit/blob/master/src/jquery.stickit.js#L291
to
```
return this.options.scope == Scope.Parent && this.element.parent().height() <= this.element.outerHeight(false);
```
looks working. But I need more time to test.

**Comment by PieterAkkerman** [comment]
This fixed my issue! Thank you very much

**Comment by emn178** [comment]
v0.2.14 should work.
