### ISSUE TITLE
Inner Scroll

### ISSUE THREAD

**Issue by sabuz** [emn178/jquery-stickit#8]
It would be better if there was inner scroll

**Comment by emn178** [comment]
What do you mean?

**Comment by sabuz** [comment]
It would be great if the sidebar scroll down for it's end and then stand still.
Please see this http://leafo.net/sticky-kit/ for clear info.
Thanks

**Comment by emn178** [comment]
What's different with this [example](http://emn178.github.io/jquery-stickit/samples/sidebar/)?

**Comment by sabuz** [comment]
No difference when you are seeing a small widget. You will feel the
difference when you will see a tall widget that is taller than screen
resolution.
Stickit plugin does not scroll the whole sidebar first. It scroll some
portion of the sidebar and do the rest portion when the content area
comes to an end.
The example plugin do the same thing...But it has included inner
scroll option which scroll the whole sidebar first and wait for the
content area for end.
I'm requesting you to include this feature.

Thank YOU!

**Comment by emn178** [comment]
I added this feature. You can try it now.

**Comment by sabuz** [comment]
Great!
Thank YOU!
